name: Goati
favicon: null
layout_spectrum: 0.9951705229468644
typography_spectrum: 0.6992865358479321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21699307020753622
  lightness: 0.07016103691421449
  saturation: 0.09258516714908183
  rhythmicContrast: 0.6438837139867246
purpose: []
