name: Goati
favicon: null
layout_spectrum: 0.25763
typography_spectrum: 0
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Funky Little Gift Shop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#908c83'
    - '#f4f4ec'
    - '#161516'
    - '#bbb6ab'
    - '#43413e'
  brandStrength: 0
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
