name: Goati
favicon: null
layout_spectrum: 0.33059
typography_spectrum: 0
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Funky Little Gift Shop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74486311-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#a7a7a6'
    - '#ffffff'
    - '#757265'
    - '#444130'
  brandStrength: 0.375
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
