name: Goati
favicon: null
layout_spectrum: 0.89725
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcd9d4'
    - '#444130'
    - '#ffffff'
    - '#a7a7a6'
    - '#757265'
  brandStrength: 0.1875
  lightness: 0.0625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
